### ISSUE TITLE
[New API] : Library API

### ISSUE THREAD

**Issue by mdrehan369** [dishamodi0910/APIVerse#56] opened 2024-05-10 20:08 UTC
### Brief Description 🤓

The Library API will be responsible for all the task that a library performs to store the data effieciently.
**Adding Books**
**Lending Books**
**Getting Customers Registered**
**Collecting Books**
and much more

### How will you develop it?🤩

I would develop it using the powers of **Express JS** and my knowledge of APIs

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment] 2024-05-10 20:08
Greetings @mdrehan369🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gdsc to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment] 2024-05-11 16:39
Hey @Abhinav-Sharma06, The issue is already assigned and couldn't be assigned to you again.You can work on some other issue or create your own issue.🚀💗

**Comment by dishamodi0910** [comment] 2024-05-14 07:43
Hey @mdrehan369 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Closed** 2024-05-14 07:43 UTC
Labels: newapi, awesome, gssoc, level3
