### ISSUE TITLE
[New API] : Generating Random Users

### ISSUE THREAD

**Issue by soham0005** [dishamodi0910/APIVerse#119] opened 2024-05-18 21:21 UTC
### Brief Description 🤓

An API for creating Random Users with User Details which can be used as dummy users for testing purpose

### How will you develop it?🤩

Using Render Platform, as i already have experience in it

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment] 2024-05-18 21:22
Greetings @soham0005🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by soham0005** [comment] 2024-05-18 21:23
Hello @dishamodi0910, is there any expiration date for this issue?

**Comment by sahoo-subhankar** [comment] 2024-05-19 07:15
Brief Description 🤓

I propose to develop an API for generating Random Users, complete with user details, which can serve as dummy data for testing purposes in various projects.

How will I proceed?

Technology Stack: I will use Node.js and Express.js to build the API.

API Routes: I will create multiple routes for different functionalities, such as generating random users and retrieving dummy user details.

Programming Language: I will use TypeScript for better type checking and enhanced code quality. Alternatively, I can use JavaScript if preferred.

Kindly assign this task to me.

Open Source Program: GSSoC (GirlScript Summer of Code)

Code of Conduct:
I follow the [CONTRIBUTING GUIDELINES](https://github.com/dishamodi0910/APIVerse/blob/master/CONTRIBUTING.md) of this project.

**Comment by mr0nerd** [comment] 2024-05-19 17:57
/gssoc24
i want to work on yjis issue please assign it to me

**Comment by soham0005** [comment] 2024-05-19 18:22
/gssoc24
i want to work on the issue

**Comment by dishamodi0910** [comment] 2024-05-19 18:22
Hey @soham0005, The issue is already assigned and couldn't be assigned to you again.You can work on some other issue or create your own issue.🚀💗

**Closed** 2024-05-19 18:22 UTC
Labels: newapi, awesome, gssoc, level3
